// generated by stringer -type=Method -output=stringer.go; DO NOT EDIT

package chess

import "fmt"

const _Method_name = "NoMethodCheckmateResignationDrawOfferStalemate"

var _Method_index = [...]uint8{0, 8, 17, 28, 37, 46}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return fmt.Sprintf("Method(%d)", i)
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
